### ISSUE TITLE
Port over Stability Evaluation code from Previous RepNoise Project [Dom]

### ISSUE THREAD

**Issue by domenicrosati** [domenicrosati/training-time-domain-authorization#3]
This includes:
- Trainability on GEM
- Using LM Harness to evaluate model capability
- We should also have some Perpelcity Measure on WikiText2 or something as people keep asking about it.

## ToDo:
- [ ] Add GEM Trainability
- [ ] Add LM Harness code
- [ ] Add Perplexity Measure

**Comment by domenicrosati** [comment]
I think another thing that is very valuable is somehow develop metrics on the fluency of the method.
LM Harness isn't really great at understanding the impact of fluecny and impact of a method on long form generation.
