### ISSUE TITLE
Architecture Design Doc and Package / Benchmark Recommendations [Harsh]

### ISSUE THREAD

**Issue by domenicrosati** [domenicrosati/training-time-domain-authorization#7]
## Issue

In order to make the package usable, extendable, an attractive for researchers it will need to be easy to read, use, and extend.

## ToDo
- [x] Propose a design doc of how the code should be architected so its clearly easy to use and extend (outcome - google doc or markdown doc for this repo)
- [ ] Clean up any current code so it conforms to this guideline (outcome - PR that organizes code so that it looks like above)
- [ ] Add PyPi package and other tooling to make the benchmark easy to run and maintain (outcome - PR that gets the code ready for a package, adds tooling)
- [ ] Add open source experience stuff like contributing.md - license, etc.

**Comment by domenicrosati** [comment]
Make sure the benchmark is easy for the user!

**Comment by domenicrosati** [comment]
@harsh  - Design Doc

**Comment by domenicrosati** [comment]
Old Notes:
- Apply for Center for AI Safety Compute Grant
- Add WANDB and add it to Github
- Provide opinionated architecture advicce / strucutre on our code
- Add dev tooling other than Ruff / Poetry
- Other things
- Turn into a PyPi package?

Make sure the benchmark is easy for the user!
We need to be sensative to create high quality easy to use code so that the bechmark is easily useable by the community
