### ISSUE TITLE
Minimum Viable Experiment [Dom]

### ISSUE THREAD

**Issue by domenicrosati** [domenicrosati/training-time-domain-authorization#9]
## Issue

Implement an experiment that illustrates repnoise on medical and legal advice

## ToDo:
- [ ] Finish implementation PR (dom)
- [ ] Add Medical Datasets (dom)
- [ ] Organize code to implement experiments in the style of repnoise paper (dom)
- [ ] Report results in paper write up that we have (dom)
